version: '3.7'
services:
  mongodb_container_2000:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db



volumes:
  mongodb_data_container: